# Generated by Django 4.2.8 on 2024-01-31 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=30, verbose_name='Тип платежа')),
                ('account_or_card_type', models.CharField(max_length=30, verbose_name='Тип карты/счёта')),
                ('owner_name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('limit_amount', models.PositiveIntegerField(verbose_name='Лимит')),
            ],
            options={
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ожидает оплаты', max_length=15, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('payment_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoices.paymentdetail', verbose_name='Реквизиты')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='invoices.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
