# Generated by Django 4.2.8 on 2024-01-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='account_or_card_type',
            field=models.CharField(max_length=50, verbose_name='Тип карты/счёта'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='owner_name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(max_length=50, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
